services:
    _defaults:
        autoconfigure: true
        public: true


    numero2_proper_filenames.listener.data_container.files:
        class: numero2\ProperFilenamesBundle\EventListener\DataContainer\FilesListener

    numero2_proper_filenames.listener.data_container.settings:
        class: numero2\ProperFilenamesBundle\EventListener\DataContainer\SettingsListener


    numero2_proper_filenames.listener.hooks.check_filenames:
        class: numero2\ProperFilenamesBundle\EventListener\Hooks\CheckFilenamesListener
        arguments:
            - '@request_stack'
            - '@router'
            - '@contao.routing.scope_matcher'
            - '@contao.translation.translator'